source 'https://rubygems.org'

gem 'coffee-rails',       '~> 4.0.0'
gem 'configliere'
gem 'devise',             '~> 3.3.0'
gem 'jquery-rails'
gem 'omniauth',           '~> 1.2.2'
gem 'omniauth-twitter'
gem 'pg'
gem 'rails',              '4.0.9'
gem 'sass-rails',         '~> 4.0.2'
gem 'uglifier',           '>= 1.3.0'
